#!/usr/bin/env python3
"""Generate the local GitHub Linguist language color map."""

from __future__ import annotations

import argparse
import ast
import json
import re
import urllib.request
from pathlib import Path

SOURCE_URL = "https://raw.githubusercontent.com/github-linguist/linguist/master/lib/linguist/languages.yml"
ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "data" / "language-colors.ts"


def decode_key(raw: str) -> str:
    raw = raw.strip()
    if raw[:1] in {'"', "'"}:
        return str(ast.literal_eval(raw))
    return raw


def parse_colors(text: str) -> dict[str, str]:
    colors: dict[str, str] = {}
    current: str | None = None
    for line in text.splitlines():
        if line and not line.startswith((" ", "#")) and line.endswith(":"):
            current = decode_key(line[:-1])
            continue
        match = re.match(r'^  color:\s*["\']?(#[0-9A-Fa-f]{6})["\']?\s*$', line)
        if current and match:
            colors[current] = match.group(1)
    return dict(sorted(colors.items(), key=lambda item: item[0].casefold()))


def ts_key(value: str) -> str:
    if re.fullmatch(r"[A-Za-z_$][A-Za-z0-9_$]*", value):
        return value
    return json.dumps(value, ensure_ascii=False)


def render_typescript(colors: dict[str, str]) -> str:
    entries = "\n".join(
        f"  {ts_key(language)}: {json.dumps(color)},"
        for language, color in colors.items()
    )
    return "\n".join(
        [
            "// Generated by scripts/update-language-colors.py.",
            f"// Source: {SOURCE_URL}",
            "// Do not edit manually.",
            "",
            "export const LANGUAGE_COLORS: Readonly<Record<string, `#${string}`>> = {",
            entries,
            "};",
            "",
            "export function languageColor(language: string | null): `#${string}` | null {",
            "  return language ? (LANGUAGE_COLORS[language] ?? null) : null;",
            "}",
            "",
        ]
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    if args.input:
        text = args.input.read_text(encoding="utf-8")
    else:
        with urllib.request.urlopen(SOURCE_URL, timeout=30) as response:
            text = response.read().decode("utf-8")
    colors = parse_colors(text)
    if len(colors) < 500:
        raise SystemExit(f"Refusing to write incomplete map: {len(colors)} colors")
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render_typescript(colors), encoding="utf-8")
    print(f"generated {len(colors)} colors -> {args.output}")


if __name__ == "__main__":
    main()
